[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["./destinations.json"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
