[build]
  functions = "netlify/functions"

[functions]
  included_files = ["./destinations.json"]

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/farcaster.json"
  status = 200

[[redirects]]
  from = "/.netlify/functions/reveal"
  to = "/.netlify/functions/reveal"
  status = 200
