[build]
  functions = "netlify/functions"

[functions]
  included_files = ["./destinations.json"]

[[redirects]]
  from = "/.well-known/farcaster.json"
  to = "/farcaster.json"
  status = 200

[[headers]]
  for = "/farcaster.json"
  [headers.values]
    Content-Type = "application/json"
